### ISSUE TITLE
Electronのアプリケーションで、通常のAltキー空打ちの操作がキャンセルされない

### ISSUE THREAD

**Issue by KHiyowa** [karakaram/alt-ime-ahk#10]
Electronのアプリケーション(Skype 8以降、Slack、1Password 7など)で、Altキーを空打ちすると、IMの状態が変わると同時に上部のメニューにキーボードショートカットのヒントが出て、次の入力を阻害してしまう。

**Comment by karakaram** [comment]
こちらから最新版をダウンロードしてご確認いただけますか。
https://github.com/karakaram/alt-ime-ahk/releases/tag/v0.4.3

私の環境（Windows 10 Pro 64bit 1803 OSビルド 17134.765）、Slack（4.2.0 64-bit）では動作しております。

**Comment by karakaram** [comment]
環境依存の問題がありそうですので、こちらでも調べてみます。

**Comment by karakaram** [comment]
以下の組み合わせで動作することを確認いたしました。

Windows10 10.0.1863
alt-ime-ahk v0.4.4
Skype v8.61.0.100

最新版に上げてみてください。
