### ISSUE TITLE
Firefox 52.6.0（Windows 10，64ビット）で動作しない

### ISSUE THREAD

**Issue by esumii** [karakaram/alt-ime-ahk#3]
GitHubのIssuesが場違いでしたらすみません。便利に利用させていただき助かっているのですが、
（少なくとも私の64ビットWindows 10 Proバージョン1709，OSビルド16299.192上の）
Firefox 52.6.0 (esr)で動作しないようです。右Altや左Altだけ押しても何も起きず
普通のIME切り替え（英語キーボードなのでAlt+`）しかできない状態です。
他のアプリケーションでは正常に動作しています。

少しWeb検索すると「Firefox 54.0から動作しない」との記事もあります。
https://qiita.com/momoyamas/items/bfe007b750f0666dae21

AutoHotkeyとIME.ahkを利用しているとのことで、それらの問題なのかもしれませんが
少し調べただけでは、すぐにはわかりませんでした。

alt-ime-ahkはv0.3.0です。

どなたか同様の問題は再現（できれば解決）されていないでしょうか…？

**Comment by karakaram** [comment]
ゆっくりですが頑張ります。
調べたことを忘れないようにメモしていきます。
随時更新していきます。
https://sites.google.com/site/autohotkeyjp/reference/commands/ControlGet

**Comment by karakaram** [comment]
@esumii
ご連絡が遅くなりました。
私の環境で動作確認したところ、Firefox上でも動作しているのですが、@esumiさんの環境ではいかがでしょうか。

- 64ビットWindows 10 Homeバージョン1709，OSビルド16299.431
- Firefox60.02
- [alt-ime-ahk0.4.0](https://github.com/karakaram/alt-ime-ahk/releases/tag/v0.4.0)

**Comment by esumii** [comment]
遅くなりましたが、私も以下の環境で正常に動作しました！
- 64ビット Windows 10 Pro バージョン1803 OSビルド17134.285
- Firefox Quantum 62.0.3 (64 ビット)
- alt-ime-ahk-v0.4.0
非常に便利です。本当にありがとうございます。
