### ISSUE TITLE
Thunderbirdで機能しない

### ISSUE THREAD

**Issue by yesman99** [karakaram/alt-ime-ahk#4]
開発者様

いつも便利に使用させていただいています。
なぜかThunderbirdで文字入力をしている時だけIMEが切り替わらなくなってしまいます。

当方の環境はWindows10・Thunderbird（52.6.0）です。

どなたか対応された方いらっしゃいましたら、ご共有いただけるとありがたいです。

**Comment by karakaram** [comment]
@yesman99 
お返事が大変遅くなりました。
[alt-ime-ahk の最新版 v0.4.1](https://github.com/karakaram/alt-ime-ahk/releases/tag/v0.4.1) と [Mozilla Thunderbird の最新版 60.3.3](https://www.thunderbird.net/en-US/) で IMEが切り替わることを確認しました。
最新版をダウンロードして試してみてください。

**Comment by yesman99** [comment]
@karakaram 
ありがとうございます。確認できました。便利に使用させていただきます。
